modLoader = "javafml"
loaderVersion = "[${loader_version},)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/IntelligenceModding/AdvancedPeripherals/issues"
logoFile = "pack.png"
[[mods]]
modId = "advancedperipherals"
version = "0.0.0"
displayName = "Advanced Peripherals (ID only)"
displayURL = "https://docs.intelligence-modding.de/"
description = "Does nothing"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Advanced Peripherals"
displayURL = "https://docs.intelligence-modding.de/"
authors = "Srendi"
description = '''
Light version of Advanced Peripherals
'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "computercraft"
mandatory = true
versionRange = "[${cc_version},)"
ordering = "NONE"
side = "BOTH"
