name: Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: build-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  generate-artifact-name:
    runs-on: self-hosted
    outputs:
      name: ${{ steps.name.outputs.name }}
    steps:
      - name: Generate Name
        id: name
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            suffix="PR ${{ github.event.number }}"
          else
            if [[ "${{ github.event_name }}" == 'push' ]]; then
              if gh search prs --json isPullRequest --jq '.[].isPullRequest' "${{ github.sha }}" | grep -m 1 true; then
                echo "name=" >> "$GITHUB_OUTPUT"
                exit 0
              fi
            fi
            ref="${{ github.ref }}"
            ref="${ref#refs/heads/}"
            suffix="${ref//\//-}"
          fi
          name="AdvancedPeripherals $suffix"
          echo "name: $name"
          echo "name=$name" >> "$GITHUB_OUTPUT"

  build-and-test:
    if: ${{ needs.generate-artifact-name.outputs.name != '' }}
    needs:
      - generate-artifact-name
    uses: IntelligenceModding/actions/.github/workflows/build-and-test.yaml@master
    with:
      build_name: ${{ needs.generate-artifact-name.outputs.name }}
      pr: ${{ github.event_name == 'pull_request' && github.event.number || '' }}
      check: ${{ github.event_name != 'push' }}

  publish:
    if: ${{ github.event_name == 'push' && contains(github.ref, 'release/') }}
    runs-on: self-hosted
    needs:
      - build-and-test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Download Builds
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-and-test.outputs.artifact-name }}
          path: build/libs
      - name: Patch Changelog
        run: ./gradlew patchChangelog
      - name: Github Release
        run: ./gradlew githubRelease
      - name: Publish Maven
        run: ./gradlew publishAllPublicationsToPublicRepository
      - name: Publish Modrinth
        run: ./gradlew modrinth
      - name: Publish CurseForge
        run: ./gradlew publishCurseForge
