name: Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-test:
    uses: IntelligenceModding/actions/.github/workflows/build-and-test.yaml@master
    with:
      build: ${{ github.event_name != 'push' }}
      build_name: AdvancedPeripherals
      pr: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || '' }}
